name: lwm


### 但是如果 backticks 混在 html 标签中,还是得用 {% highlight %}
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]



gems:
  - jekyll-sitemap

# 更改这个配置文件需要重启一下
destination: /cygdrive/r/_site



include: []

exclude: ['*.md','*.less','assets/css/metro-bootstrap.css','assets/css/bootstrap.css','Thumbs.db']

keep_files: ['.git','.svn','_test']

encoding: utf-8

timezone: CN

excerpt_separator: <!-- more -->



# 计划用这个来实现 别人帮助 编辑
doc_url_path: https://github.com/R32/r32.github.io/blob/master/



#permalink: none


##### 一些自定义的数据

custom_menu:
  - name: home
    url: /
    label: 主页
  - name: haxe
    url: /haxe/
    label: Haxe
  - name: haxelib
    url: /haxelib/
    label: Haxelib    
  - name: other
    url: /other/
    label: 其它
  - name: person
    url: /person/
    label: 个人


powered_by:
  - name: Github Pages
    url: pages.github.com
  - name: Metro Bootstrap
    url: talkslab.github.io/metro-bootstrap

