name: 5515544's Blog

#markdown: redcarpet
markdown: kramdown

#pygments: true

gems:
  - jekyll-sitemap

# 更改这个配置文件需要重启一下
destination: /cygdrive/r/_site

include: []

exclude: ['*.md','*.less','assets/css/metro-bootstrap.css','assets/css/bootstrap.css']

keep_files: ['.git','.svn','_test']

encoding: utf-8

timezone: CN

excerpt_separator: <!-- more -->

# 计划用这个来实现 别人帮助 编辑
doc_url_path: https://github.com/R32/blog/blob/master/

#permalink: none
#header menu config

custom_menu:
  - name: home
    url: /
    label: 主页
  - name: haxe
    url: /haxe/
    label: Haxe
  - name: other
    url: /other/
    label: 其它
  - name: person
    url: /person/
    label: 个人
  - name: forum
    url: /forum/
    label: 留言
# powered by ...
powered_by:
  - name: Github Pages
    url: pages.github.com
  - name: Metro Bootstrap
    url: talkslab.github.io/metro-bootstrap

